
Fri, 06/04/21, 09:35:45:%f AM:  
    PROGRAM START
    -------------

    Config used: 
        - config file name : configs/presto/presto_full.txt
        - repo             : prestodb/presto
        - branch name      : master
        - session          : <github.MainClass.Github object at 0x7f9ce8b63e50>
        - rows             : all
        - issue state      : closed        
        - pr state         : closed          
        - diagnostics      : True          
        - log file         : log_files/presto/presto_full_log.txt        

        - issue json file  : outputs/presto/presto_full_issues.json
        - pr JSON file     : outputs/presto/presto_full_prs.json
        - commit JSON file : outputs/presto/presto_full_commits.json

        - "pr" CSV file    : outputs/presto/presto_full_pr_output.csv       
        - "commit" CSV file: outputs/presto/presto_full_commit_output.csv


Fri, 06/04/21, 09:35:49:%f AM: 
Attempting program start...

Fri, 06/04/21, 09:35:49:%f AM: 
    Getting paginated list of issues...

Fri, 06/04/21, 09:35:49:%f AM: 
        Complete!

Fri, 06/04/21, 09:35:49:%f AM: 
    Getting paginated list of pull requests...

Fri, 06/04/21, 09:35:49:%f AM: 
        Complete!

Fri, 06/04/21, 09:35:49:%f AM: 
    Getting issue data...

Fri, 06/04/21, 09:48:54:%f AM: 
    Rate Limit imposed. Sleeping...
Traceback (most recent call last):
  File "/home/j/git/GitHub-Repo-Extractor/extractor.py", line 574, in get_issue_info
    if comments_paged_list.totalCount == 0:
  File "/home/j/.local/lib/python3.9/site-packages/github/PaginatedList.py", line 149, in totalCount
    headers, data = self.__requester.requestJsonAndCheck(
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 353, in requestJsonAndCheck
    return self.__check(
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 378, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.RateLimitExceededException: 403 {"message": "API rate limit exceeded for user ID 78055520.", "documentation_url": "https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}

Fri, 06/04/21, 10:35:55:%f AM: 
    Getting more issue info...

Fri, 06/04/21, 10:49:12:%f AM: 
    Rate Limit imposed. Sleeping...
Traceback (most recent call last):
  File "/home/j/git/GitHub-Repo-Extractor/extractor.py", line 578, in get_issue_info
    if cur_issue.closed_at is not None:
  File "/home/j/.local/lib/python3.9/site-packages/github/PaginatedList.py", line 56, in __iter__
    newElements = self._grow()
  File "/home/j/.local/lib/python3.9/site-packages/github/PaginatedList.py", line 67, in _grow
    newElements = self._fetchNextPage()
  File "/home/j/.local/lib/python3.9/site-packages/github/PaginatedList.py", line 199, in _fetchNextPage
    headers, data = self.__requester.requestJsonAndCheck(
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 353, in requestJsonAndCheck
    return self.__check(
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 378, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.RateLimitExceededException: 403 {"message": "API rate limit exceeded for user ID 78055520.", "documentation_url": "https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}

Fri, 06/04/21, 11:36:00:%f AM: 
    Getting more issue info...

Fri, 06/04/21, 11:49:08:%f AM: 
    Rate Limit imposed. Sleeping...
Traceback (most recent call last):
  File "/home/j/git/GitHub-Repo-Extractor/extractor.py", line 557, in get_issue_info
    log_and_print( "G_DATA_ISSUE", "INFO", logger )
  File "/home/j/.local/lib/python3.9/site-packages/github/NamedUser.py", line 276, in name
    self._completeIfNotSet(self._name)
  File "/home/j/.local/lib/python3.9/site-packages/github/GithubObject.py", line 297, in _completeIfNotSet
    self._completeIfNeeded()
  File "/home/j/.local/lib/python3.9/site-packages/github/GithubObject.py", line 301, in _completeIfNeeded
    self.__complete()
  File "/home/j/.local/lib/python3.9/site-packages/github/GithubObject.py", line 308, in __complete
    headers, data = self._requester.requestJsonAndCheck("GET", self._url.value)
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 353, in requestJsonAndCheck
    return self.__check(
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 378, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.RateLimitExceededException: 403 {"message": "API rate limit exceeded for user ID 78055520.", "documentation_url": "https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}

Fri, 06/04/21, 12:36:04:%f PM: 
    Getting more issue info...

Fri, 06/04/21, 12:49:24:%f PM: 
    Rate Limit imposed. Sleeping...
Traceback (most recent call last):
  File "/home/j/git/GitHub-Repo-Extractor/extractor.py", line 557, in get_issue_info
    # get info from curret issue
  File "/home/j/.local/lib/python3.9/site-packages/github/NamedUser.py", line 276, in name
    self._completeIfNotSet(self._name)
  File "/home/j/.local/lib/python3.9/site-packages/github/GithubObject.py", line 297, in _completeIfNotSet
    self._completeIfNeeded()
  File "/home/j/.local/lib/python3.9/site-packages/github/GithubObject.py", line 301, in _completeIfNeeded
    self.__complete()
  File "/home/j/.local/lib/python3.9/site-packages/github/GithubObject.py", line 308, in __complete
    headers, data = self._requester.requestJsonAndCheck("GET", self._url.value)
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 353, in requestJsonAndCheck
    return self.__check(
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 378, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.RateLimitExceededException: 403 {"message": "API rate limit exceeded for user ID 78055520.", "documentation_url": "https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}

Fri, 06/04/21, 01:36:10:%f PM: 
    Getting more issue info...

Fri, 06/04/21, 01:49:10:%f PM: 
    Rate Limit imposed. Sleeping...
Traceback (most recent call last):
  File "/home/j/git/GitHub-Repo-Extractor/extractor.py", line 574, in get_issue_info
  File "/home/j/.local/lib/python3.9/site-packages/github/PaginatedList.py", line 149, in totalCount
    headers, data = self.__requester.requestJsonAndCheck(
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 353, in requestJsonAndCheck
    return self.__check(
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 378, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.RateLimitExceededException: 403 {"message": "API rate limit exceeded for user ID 78055520.", "documentation_url": "https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}

Fri, 06/04/21, 02:36:15:%f PM: 
    Getting more issue info...

Fri, 06/04/21, 02:49:10:%f PM: 
    Rate Limit imposed. Sleeping...
Traceback (most recent call last):
  File "/home/j/git/GitHub-Repo-Extractor/extractor.py", line 557, in get_issue_info
  File "/home/j/.local/lib/python3.9/site-packages/github/NamedUser.py", line 276, in name
    self._completeIfNotSet(self._name)
  File "/home/j/.local/lib/python3.9/site-packages/github/GithubObject.py", line 297, in _completeIfNotSet
    self._completeIfNeeded()
  File "/home/j/.local/lib/python3.9/site-packages/github/GithubObject.py", line 301, in _completeIfNeeded
    self.__complete()
  File "/home/j/.local/lib/python3.9/site-packages/github/GithubObject.py", line 308, in __complete
    headers, data = self._requester.requestJsonAndCheck("GET", self._url.value)
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 353, in requestJsonAndCheck
    return self.__check(
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 378, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.RateLimitExceededException: 403 {"message": "API rate limit exceeded for user ID 78055520.", "documentation_url": "https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}

Fri, 06/04/21, 03:36:22:%f PM: 
    Getting more issue info...

Fri, 06/04/21, 03:49:25:%f PM: 
    Rate Limit imposed. Sleeping...
Traceback (most recent call last):
  File "/home/j/git/GitHub-Repo-Extractor/extractor.py", line 574, in get_issue_info
    issue_info_list = [
  File "/home/j/.local/lib/python3.9/site-packages/github/PaginatedList.py", line 149, in totalCount
    headers, data = self.__requester.requestJsonAndCheck(
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 353, in requestJsonAndCheck
    return self.__check(
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 378, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.RateLimitExceededException: 403 {"message": "API rate limit exceeded for user ID 78055520.", "documentation_url": "https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}

Fri, 06/04/21, 04:36:29:%f PM: 
    Getting more issue info...

Fri, 06/04/21, 04:49:17:%f PM: 
    Rate Limit imposed. Sleeping...
Traceback (most recent call last):
  File "/home/j/git/GitHub-Repo-Extractor/extractor.py", line 574, in get_issue_info
    issue_info_list = [
  File "/home/j/.local/lib/python3.9/site-packages/github/PaginatedList.py", line 149, in totalCount
    headers, data = self.__requester.requestJsonAndCheck(
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 353, in requestJsonAndCheck
    return self.__check(
  File "/home/j/.local/lib/python3.9/site-packages/github/Requester.py", line 378, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.RateLimitExceededException: 403 {"message": "API rate limit exceeded for user ID 78055520.", "documentation_url": "https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}

Fri, 06/04/21, 05:36:35:%f PM: 
    Getting more issue info...

Fri, 06/04/21, 05:43:05:%f PM: 
        Complete!

Fri, 06/04/21, 05:43:05:%f PM: 
    Writing list of issue data to JSON...

Fri, 06/04/21, 05:43:05:%f PM: 
    Unspecified exception:

Traceback (most recent call last):
  File "/home/j/git/GitHub-Repo-Extractor/extractor.py", line 111, in main
  File "/home/j/git/GitHub-Repo-Extractor/extractor.py", line 285, in exe_menu
    # read metalists out of JSON storage
  File "/home/j/git/GitHub-Repo-Extractor/extractor.py", line 651, in get_issue_json
    #                   - desc: if "remaining", contains remaining requests for
  File "/home/j/git/GitHub-Repo-Extractor/extractor.py", line 1073, in json_io
    "G_MORE_COMMIT" : getter + "more commit data...",
FileNotFoundError: [Errno 2] No such file or directory: 'outputs/presto/presto_full_issues.json'

Fri, 06/04/21, 05:43:05:%f PM: 
    END OF PROGRAM RUN

------------------------------------------------------------------------------

