
06/02/21, 07:35:49 PM:  
    PROGRAM START
    -------------

    Config used: 
        - config file name : configs/trouble.txt
        - repo             : folke/trouble.nvim
        - branch name      : default
        - session          : <github.MainClass.Github object at 0x7f75ebf07340>
        - rows             : all
        - issue state      : closed        
        - pr state         : closed          
        - diagnostics      : True          
        - log file         : log_files/trouble.txt        

        - issue json file  : json_files/issue_full_trouble.json
        - pr JSON file     : json_files/pr_full_trouble.json
        - commit JSON file : json_files/commit_full_trouble.json

        - "pr" CSV file    : prog_runs/pr_full_trouble.csv       
        - "commit" CSV file: prog_runs/commit_full_trouble.csv

06/02/21, 07:35:51 PM: 
    Acquiring paginated list of pull requests.

06/02/21, 07:35:51 PM: 
    Acquiring pull request data and paginated list of commits.

06/02/21, 07:36:01 PM: 
    Writing pull request data to JSON.

06/02/21, 07:36:01 PM: 
    Uncaught exception:

Traceback (most recent call last):
  File "/home/j/git/GitHub-Repo-Extractor/test/test_ext.py", line 168, in main
    exe_menu( conf_list, logger )
  File "/home/j/git/GitHub-Repo-Extractor/test/test_ext.py", line 295, in exe_menu
    get_PR_commit_json( session, pr_paged_list, row_quant,
  File "/home/j/git/GitHub-Repo-Extractor/test/test_ext.py", line 855, in get_PR_commit_json
    json_io( pr_json_filename, 'w', pr_info_metalist )
  File "/home/j/git/GitHub-Repo-Extractor/test/test_ext.py", line 1071, in json_io
    with open( file_name, mode ) as json_file:
FileNotFoundError: [Errno 2] No such file or directory: 'json_files/issue_full_trouble.json'

06/02/21, 07:36:01 PM: 
    END OF PROGRAM RUN

------------------------------------------------------------------------------

